CREATE TABLE SP_CUSTOMER04A (
	CUSTOMER_NO int NOT NULL PRIMARY KEY,
	FIRST_NAME char (32)  NOT NULL ,
	LAST_NAME char (32)  NOT NULL ,
	PHONE_NUMBER char (32)  NULL ,
	ADDRESS char (255)  NULL ,
	EMAIL char (32)  NOT NULL ,
	CREDIT_LIMIT int NOT NULL )
GO


