CREATE TABLE SP_CUSTOMER04A (
	CUSTOMER_NO int NOT NULL ,
	FIRST_NAME char (32)  ,
	LAST_NAME char 
	PHONE_NUMBER char (32)  ,
	ADDRESS char (255)  ,
	EMAIL char (32)  ,
	CREDIT_LIMIT int NOT NULL ,
) ON PRIMARY
GO

CREATE TABLE SP_ACCOUNT04A (
	ACCOUNT_ID int NOT NULL ,
	CUSTOMER_NO int NOT NULL ,
	CURRENCY char (10)  ,
	TYPE char (1)  ,
	BALANCE decimal(18, 3) NOT NULL
	)
GO


drop procedure SP_ADD_ACCOUNT;
create procedure SP_ADD_ACCOUNT
	@ACCOUNT_ID int OUTPUT,
	@CUSTOMER_NO int,
	@TYPE char (1),
	@CURRENCY char (10),
	@BALANCE  decimal (18, 3)
as
--declare @ACCOUNT_ID int
begin
set @ACCOUNT_ID = (SELECT max(ACCOUNT_ID) + 1 FROM SP_ACCOUNT04A);
INSERT INTO SP_ACCOUNT04A ( ACCOUNT_ID, CUSTOMER_NO, TYPE, CURRENCY, BALANCE )
	VALUES ( @ACCOUNT_ID, @CUSTOMER_NO, @TYPE, @CURRENCY, @BALANCE );
--  return @ACCOUNT_ID;
end;

