DROP TABLE IF EXISTS SP_CUSTOMER04A;
DROP TABLE IF EXISTS SP_ACCOUNT04A;

CREATE TABLE SP_CUSTOMER04A (
	CUSTOMER_NO int NOT NULL primary key,
	FIRST_NAME char (32) NOT NULL ,
	LAST_NAME char (32) NOT NULL ,
	PHONE_NUMBER char (32) NULL ,
	ADDRESS char (255) NULL ,
	EMAIL char (32) NOT NULL ,
	CREDIT_LIMIT int NOT NULL 
);

CREATE TABLE SP_ACCOUNT04A (
	ACCOUNT_ID int NOT NULL primary key,
	CUSTOMER_NO int NOT NULL ,
	CURRENCY char (10) NOT NULL ,
	TYPE char (1) NOT NULL ,
	BALANCE decimal(18, 3) NOT NULL
);


drop procedure if exists SP_ADD_ACCOUNT;

DELIMITER //
CREATE PROCEDURE SP_ADD_ACCOUNT
(	OUT ACCT_ID int,
	IN CUSTOMER_NO int,
	IN TYPE char (1),
	IN CURRENCY char (10),
	IN BALANCE  decimal (18, 3) )
BEGIN
	set ACCT_ID = (SELECT max(ACCOUNT_ID) + 1 FROM SP_ACCOUNT04A);
	if isnull(ACCT_ID) then
		set ACCT_ID = 0;
	end if;
		
	
	INSERT INTO SP_ACCOUNT04A ( ACCOUNT_ID, CUSTOMER_NO, TYPE, CURRENCY, BALANCE )
		VALUES ( ACCT_ID, CUSTOMER_NO, TYPE, CURRENCY, BALANCE );
END //
DELIMITER ;

-- CALL SP_ADD_ACCOUNT (@ACCT_ID, 1, 'S', 'CAD', 1000.0);
